config/routes.rb
Rails.application.routes.draw do
  get 'pages/batman-vs-superman'
  post 'pages/votos_superman'
  post 'pages/votos_batman'
  get 'pages/batman'
  get 'pages/superman'
  root 'pages#batman-vs-superman'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/voto.rb
class Voto < ApplicationRecord
end

app/models/votos_batman.rb
class VotosBatman < ApplicationRecord
end

app/models/votos_superan.rb
class VotosSuperan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  	

  end

  def superman
  	
  	
  end

 

  def votos_superman
  	if  params[:name].present? && params[:email].present?
  		user = User.new
  		user.name = params [:name]
  		user.email = params [:email]
  		user.save
  	redirect_to rooth_path, notice: "Voto aceptado"
	
  	end	
  	
  end

  def votos_batman
  	redirect_to  rooth_path
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/batman-vs-superman.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<style>
	
.superman {

	display: inline;

}

.superman img {

	width: 50%;
	height: 400px;
	display: inline;
	float: left;
	

}

.batman {

	
	display: inline;
	height: 400px;


}

.batman img {

	width: 50%;
	height: 400px;
	display: inline;
	float: right;
	

	
	
}

.votosbatman {

	margin-left: 50%;
}

.votosuperman {

	float: left;
}


</style>
</head>
<body>


<div class="superman"> <a href="http://localhost:3000/pages/superman"><img src="<%= asset_path 'superman.jpeg' %>" alt=""></a>

</div>

</div>



<div class="batman"> <a href="http://localhost:3000/pages/batman"><img src="<%= asset_path 'thumb-1920-82331.jpg' %>" alt=""> </a> 

</div>

<div class="votosuperman"><%= form_tag(pages_votos_superman_path) do %>
	<%= text_field_tag "votosuperman", nil, placeholder: "Nombre"  %> <br>
	<%= email_field_tag "votosbatman", nil, placeholder: "Email"  %> <br> 
	<%= submit_tag "Votar" %>

	<div class="notice"> <%= notice %></div>
	
<% end -%>
</div>

<div class="votosbatman"> <%= form_tag(pages_votos_batman_path) do %>
	<%= text_field_tag "name", nil, placeholder: "Nombre"  %> <br>
	<%= email_field_tag "email", nil, placeholder: "Email"  %> <br> 
	<%= submit_tag "Votar" %>
	
<% end -%>










</body>
</html> 

app/views/pages/batman.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<style>
	
body {

	background: url(<%= asset_path 'thumb-1920-82331.jpg' %>)
}

.texto {

	color: white;
}


</style>
</head>
<body>

<h1 class="texto">This looks like a job Superman</h1>


</body>
</html> 

app/views/pages/superman.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<style>
	
body {

	background: url(<%= asset_path 'superman.jpeg' %>)
}


</style>
</head>
<body>

<h1>This looks like a job Superman</h1>


</body>
</html> 